"""Pydantic models for delivery receipt data."""

from datetime import datetime
from typing import Optional
from zoneinfo import ZoneInfo
from pydantic import BaseModel, Field, field_validator

# Jakarta timezone (UTC+7)
JAKARTA_TZ = ZoneInfo("Asia/Jakarta")


class DeliveryReceiptData(BaseModel):
    """Raw data extracted from delivery weighing receipt via Gemini."""

    receipt_number: str = Field(..., min_length=1, description="NO NOTA - Receipt/Note number")
    scale_number: str = Field(..., min_length=1, description="NOMOR TIMBANGAN - Scale number")
    weighing_datetime: str = Field(..., description="WAKTU PENIMBANGAN - Weighing date and time in YYYY-MM-DD HH:MM:SS format")
    vehicle_number: str = Field(..., min_length=1, description="NOMOR UNIT - Vehicle registration number")
    material_name: str = Field(..., min_length=1, description="NAMA MATERIAL - Type of material/boulder")
    gross_weight: float = Field(..., gt=0, description="BERAT ISI - Gross weight in tons")
    empty_weight: float = Field(..., ge=0, description="BERAT KOSONG - Empty vehicle weight in tons")
    net_weight: float = Field(..., gt=0, description="BERAT BERSIH - Net material weight in tons")
    confidence_score: float = Field(default=1.0, ge=0.0, le=1.0)
    material_type: str = Field(default="Lainnya", description="Categorized material type")

    @field_validator("weighing_datetime")
    @classmethod
    def validate_datetime_format(cls, v: str) -> str:
        """Ensure datetime is in YYYY-MM-DD HH:MM:SS format."""
        try:
            datetime.strptime(v, "%Y-%m-%d %H:%M:%S")
            return v
        except ValueError:
            raise ValueError(f"Datetime must be in YYYY-MM-DD HH:MM:SS format, got: {v}")

    @field_validator("net_weight")
    @classmethod
    def validate_net_weight(cls, v: float, info) -> float:
        """Validate net weight is positive."""
        if v <= 0:
            raise ValueError("Net weight must be greater than 0")
        return v


class DeliveryRecord(BaseModel):
    """Complete delivery record for Google Sheets."""

    timestamp: datetime = Field(default_factory=lambda: datetime.now(JAKARTA_TZ))
    receipt_number: str = Field(..., min_length=1)
    weighing_datetime: str = Field(..., description="Weighing date and time")
    scale_number: str = Field(..., min_length=1)
    vehicle_number: str = Field(..., min_length=1)
    material_name: str = Field(..., min_length=1)
    material_type: str = Field(default="Lainnya", description="Categorized material type")
    gross_weight: float = Field(..., gt=0, description="Weight in tons")
    empty_weight: float = Field(..., ge=0, description="Weight in tons")
    net_weight: float = Field(..., gt=0, description="Weight in tons")
    status: str = Field(default="Delivered")
    notes: str = Field(default="")
    receipt_url: str = Field(default="")  # Google Drive link
    confidence: float = Field(default=1.0, ge=0, le=1.0)

    @classmethod
    def from_receipt_data(
        cls,
        receipt: DeliveryReceiptData,
        material_type: Optional[str] = None,
        confidence: float = 1.0,
        receipt_url: str = "",
        notes: str = ""
    ) -> "DeliveryRecord":
        """Create DeliveryRecord from DeliveryReceiptData.

        Args:
            receipt: Extracted receipt data
            material_type: Optional override for material type.
                          If not provided, uses receipt.material_type
            confidence: Confidence score
            receipt_url: URL to receipt image
            notes: Additional notes
        """
        return cls(
            receipt_number=receipt.receipt_number,
            weighing_datetime=receipt.weighing_datetime,
            scale_number=receipt.scale_number,
            vehicle_number=receipt.vehicle_number,
            material_name=receipt.material_name,
            material_type=material_type or receipt.material_type,
            gross_weight=receipt.gross_weight,
            empty_weight=receipt.empty_weight,
            net_weight=receipt.net_weight,
            status="Delivered",
            notes=notes,
            receipt_url=receipt_url,
            confidence=confidence
        )

    def to_sheets_row(self):
        """Convert to Google Sheets row format.

        Column order: No, Date, Receipt #, Time, Scale #, Vehicle #,
                     Material, Type, Gross (t), Empty (t), Net (t),
                     Status, Notes, Receipt URL, Added At
        """
        # Split weighing_datetime into date and time
        date_part = self.weighing_datetime.split()[0]  # "2025-12-24"
        time_part = self.weighing_datetime.split()[1] if len(self.weighing_datetime.split()) > 1 else "00:00:00"

        return [
            "",  # No - auto-generated by formula
            date_part,  # Date
            self.receipt_number,  # Receipt #
            time_part,  # Time
            self.scale_number,
            self.vehicle_number,
            self.material_name,
            self.material_type,
            self.gross_weight,
            self.empty_weight,
            self.net_weight,
            self.status,
            self.notes,
            self.receipt_url,
            self.timestamp.strftime("%Y-%m-%d %H:%M:%S")
        ]


class TokenUsageRecord(BaseModel):
    """Token usage record for Gemini API calls."""

    timestamp: datetime = Field(default_factory=lambda: datetime.now(JAKARTA_TZ))
    receipt_number: str = Field(default="", description="Associated receipt number")
    operation: str = Field(..., description="Operation type: extraction or categorization")
    model: str = Field(default="gemini-2.5-flash-lite")
    prompt_tokens: int = Field(default=0, description="Input tokens")
    output_tokens: int = Field(default=0, description="Output tokens")
    total_tokens: int = Field(default=0, description="Total tokens used")

    def to_sheets_row(self):
        """Convert to Google Sheets row format.

        Column order: No, Timestamp, Receipt #, Operation, Model,
                     Input Tokens, Output Tokens, Total Tokens
        """
        return [
            "",  # No - auto-generated or read from sheet
            self.timestamp.strftime("%Y-%m-%d %H:%M:%S"),
            self.receipt_number,
            self.operation,
            self.model,
            self.prompt_tokens,
            self.output_tokens,
            self.total_tokens
        ]


# Predefined material types for boulder deliveries (Indonesian)
MATERIAL_TYPES = [
    "Batu Pecah 1/2",
    "Batu Pecah 2/3",
    "Batu Pecah 3/5",
    "Batu Sungai",
    "Boulder",
    "Kerikil",
    "Pasir",
    "Abu Batu",
    "Lainnya"
]
